import Head from 'next/head';
import React, { useState } from 'react';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [data, setData] = useState([
        {
            id: 0,
            value: 0,
        },
        {
            id: 1,
            value: 0,
        },
        {
            id: 2,
            value: 0,
        },
        {
            id: 3,
            value: 0,
        },
        {
            id: 4,
            value: 0,
        },
        {
            id: 5,
            value: 0,
        },
        {
            id: 6,
            value: 0,
        },
        {
            id: 7,
            value: 0,
        },
        {
            id: 8,
            value: 0,
        }
    ]);

    const handleIncrementClick = (index, value) => {
        const nextCounters = data.map((c, i) => {
            if (i === index) {
                return {
                    id: i,
                    value: parseInt(value)
                };
            } else {
                // The rest haven't changed
                return c;
            }
        });
        setData(nextCounters);
    }

    return (
        <>
            <Head>
                <title>Diet Risk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.cardContainer}>
                    <h1 className={`${styles.headingTitle} ${inter.className}`}>Diet Risk Score Calculator</h1>
                    <div className={`${styles.grid} ${inter.className}`}>
                        <div className={styles.mainCard}>
                            <div>Fast food 🍕</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(0, e.target.value)} className={styles.selectOption}>
                                <option value="3">Daily</option>
                                <option value="2">2-3x/day</option>
                                <option value="1">1x/day</option>
                                <option value="0" selected>Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Bread, rolls 🥪</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(1, e.target.value)} className={styles.selectOption}>
                                <option value="3">Daily</option>
                                <option value="2">2-3x/day</option>
                                <option value="1">1x/day</option>
                                <option value="0" selected>Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Chips, salty snacks, pretzels 🥨</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(2, e.target.value)} className={styles.selectOption}>
                                <option value="3">Daily</option>
                                <option value="2">2-3x/day</option>
                                <option value="1">1x/day</option>
                                <option value="0" selected>Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Hot dogs, sausages 🌭</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(3, e.target.value)} className={styles.selectOption}>
                                <option value="3">Daily</option>
                                <option value="3">2-3x/day</option>
                                <option value="3">1x/day</option>
                                <option value="0" selected>Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Sweet drinks 🥤</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(4, e.target.value)} className={styles.selectOption}>
                                <option value="3">Daily</option>
                                <option value="2">2-3x/day</option>
                                <option value="1">1x/day</option>
                                <option value="0" selected>Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Peanuts, seeds, nut butter 🥜</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(5, e.target.value)} className={styles.selectOption}>
                                <option value="0" selected>Daily</option>
                                <option value="0">2-3x/day</option>
                                <option value="2">1x/day</option>
                                <option value="3">Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Fish, shellfish 🐟</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(6, e.target.value)} className={styles.selectOption}>
                                <option value="0" selected>Daily</option>
                                <option value="0">2-3x/day</option>
                                <option value="1">1x/day</option>
                                <option value="3">Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Vegetables 🥕</div>
                            <div>
                            <select onChange={(e) => handleIncrementClick(7, e.target.value)} className={styles.selectOption}>
                                <option value="0" selected>Daily</option>
                                <option value="3">2-3x/day</option>
                                <option value="3">1x/day</option>
                                <option value="3">Never</option>
                            </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Fruit 🍎</div>
                            <div>
                                <select onChange={(e) => handleIncrementClick(8, e.target.value)} className={styles.selectOption}>
                                    <option value="0" selected>Daily</option>
                                    <option value="3">2-3x/day</option>
                                    <option value="3">1x/day</option>
                                    <option value="3">Never</option>
                                </select>
                            </div>
                        </div>
                        <div className={styles.mainCard}>
                            <div>Risk score:</div>
                            <div>
                                {data.reduce((n, {value}) => n + value, 0)} <br/>
                                
                            </div>
                        </div>
                        <div>
                            {data.reduce((n, {value}) => n + value, 0) <= 10 ? '✅ Your diet risk is low.' : ''}
                            {data.reduce((n, {value}) => n + value, 0) >= 10 && data.reduce((n, {value}) => n + value, 0) < 20 ? '⚠️ Your diet risk is moderate.' : ''}
                            {data.reduce((n, {value}) => n + value, 0) >= 20  ? '🚫 Your diet risk is high.' : ''}
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}
